apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: dbuser
  labels:
    app.kubernetes.io/version: 1.6.0
spec:
  roles:
    - roleName: "readWriteAnyDatabase"
      databaseName: "admin"
  projectRef:
    name: atlas-project
  username: dbuser
  passwordSecretRef:
    name: the-user-password